name: Publish to github Pages

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: "yarn"

      - name: build dist
        run: |
          yarn install
          yarn build
          cp dist/index.html dist/404.html

      - name: publish dist
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git checkout -B tmp
          git add dist -f
          git commit -m ":rocket: Publish"
          git push origin `git subtree split --prefix dist tmp`:gh-pages --force
